Repository grafana/pySigma-backend-loki, pull requests merged in 2023-09, with the labels that each got.

#82 Update pySigma
  poetry.lock
  pyproject.toml
  sigma/backends/loki/loki.py
Labels: dependencies

#85 Sigma CLI integration testing
  .github/workflows/test.yml
  README.md
  tests/test_sigma_cli_integration.sh
  tests/test_sigma_rule.yml
Labels: enhancement

#90 Update patch versions of dependencies
  poetry.lock
Labels: dependencies

#92 Add missing `last_processing_pipeline` property to backend class initialization
  sigma/backends/loki/loki.py
Labels: bug
